name: Filter V2Ray Servers

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Filter Script
        run: python filter_servers.py
      
      # --- NEW STEP TO FIX THE ERROR ---
      # This pulls the latest changes from the repository before committing.
      - name: Pull latest changes
        run: git pull
      
      - name: Commit and Push new subscription file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update filtered subscription link"
          file_pattern: 'filtered_sub.txt'
