name: Filter V2Ray Servers with sub-checker

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Download and set up the sub-checker tool
      - name: Download and Prepare sub-checker
        run: |
          # Fetch the latest version of sub-checker for Linux
          LATEST_URL=$(curl -sL "https://api.github.com/repos/LalatinaHub/sub-checker/releases/latest" | grep -o "https://github.com/LalatinaHub/sub-checker/releases/download/v.*-linux-amd64.tar.gz")
          echo "Downloading sub-checker from ${LATEST_URL}"
          
          # Download and extract the tool
          curl -sL -o sub-checker.tar.gz "${LATEST_URL}"
          tar -xvf sub-checker.tar.gz
          
          # Make the tool executable
          chmod +x ./sub-checker
          echo "sub-checker is ready."

      # Step 3: Run sub-checker to test and filter your subscription
      - name: Run Real Connectivity Test
        run: |
          # This command does everything:
          # -sub: Your subscription link
          # -o: The output file for the filtered subscription
          # -sc 10: Runs a speed test on the fastest 10 nodes (implies a real connectivity check)
          # -t 4000: Sets a 4000ms (4 second) timeout for each test
          ./sub-checker -sub "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/vless" \
                        -o ./filtered_sub.txt \
                        -sc 10 \
                        -t 4000
        
          echo "Testing complete. Filtered list saved to filtered_sub.txt"

      # Step 4: Commit the new filtered list back to the repository
      - name: Commit and Push new subscription file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update filtered subscription with real-world tested servers"
          file_pattern: 'filtered_sub.txt'
