name: Filter V2Ray Servers

# NEW: Prevents the workflow from running multiple times at once
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # NEW: This is the most important fix.
    # It gives the workflow permission to write the new file back to your repository.
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Filter Script
        run: python filter_servers.py

      - name: Commit and Push new subscription file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update filtered subscription link" # Added an emoji to make commits clearer
          file_pattern: 'filtered_sub.txt'
